USE ROLE SYSADMIN;

DROP WAREHOUSE LAB001_WH;
DROP STAGE LAB001_DB.SCOOBY_SCHEMA.SCOOBY_ASSETS;
DROP SCHEMA LAB001_DB.SCOOBY_SCHEMA;
DROP DATABASE LAB001_DB;
USE ROLE SECURITYADMIN;
DROP ROLE LAB001_ROLE;